import { Task, Profile } from './firebase/types';

export const INITIAL_DEMO_EMPLOYEES: Profile[] = [
  {
    id: 'demo-manager-id',
    name: 'نهى العتيبي',
    email: 'noha@mahamee.local',
    role: 'manager',
    is_active: true,
    created_at: '2026-09-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'demo-employee-id',
    name: 'سارة الشمري',
    email: 'sara@mahamee.local',
    role: 'employee',
    is_active: true,
    created_at: '2026-09-02T09:30:00Z',
    updated_at: '2026-09-02T09:30:00Z',
  },
  {
    id: 'demo-employee-2',
    name: 'فاطمة الدوسري',
    email: 'fatima@mahamee.local',
    role: 'employee',
    is_active: true,
    created_at: '2026-09-03T10:15:00Z',
    updated_at: '2026-09-03T10:15:00Z',
  },
  {
    id: 'demo-employee-3',
    name: 'مريم القحطاني',
    email: 'mariam@mahamee.local',
    role: 'employee',
    is_active: true,
    created_at: '2026-09-04T11:00:00Z',
    updated_at: '2026-09-04T11:00:00Z',
  },
];

export const INITIAL_DEMO_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'تجديد عقد الصيانة السنوي لمقر الجمعية',
    description: 'مراجعة عروض أسعار شركات الصيانة واعتماد العقد النهائي وتوقيعه.',
    status: 'not_started',
    priority: 'urgent',
    due_date: '2026-09-12',
    category: 'إدارية',
    user_id: 'demo-manager-id',
    created_at: '2026-09-05T08:00:00Z',
    updated_at: '2026-09-05T08:00:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[0],
  },
  {
    id: 'task-2',
    title: 'إعداد تقرير ملتقى الجالية الفلبينية الأسبوعي',
    description: 'حصر أعداد الحضور والمهتدين الجدد وإرفاق صور الفعالية في التقرير الدوري.',
    status: 'in_progress',
    priority: 'high',
    due_date: '2026-09-10',
    category: 'برامج دعوية',
    user_id: 'demo-employee-id', // سارة
    created_at: '2026-09-05T09:00:00Z',
    updated_at: '2026-09-05T09:00:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[1],
  },
  {
    id: 'task-3',
    title: 'تنسيق الحقائب الدعوية للقوافل الميدانية',
    description: 'تجهيز 200 حقيبة دعوية بلغات متعددة لتوزيعها في الزيارات الميدانية.',
    status: 'completed',
    priority: 'medium',
    due_date: '2026-09-08',
    category: 'قوافل',
    user_id: 'demo-employee-id', // سارة
    created_at: '2026-09-04T10:00:00Z',
    updated_at: '2026-09-04T10:00:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[1],
  },
  {
    id: 'task-4',
    title: 'ترجمة مطوية أحكام الصلاة إلى اللغة الأردية',
    description: 'إتمام المراجعة اللغوية والتدقيق الشرعي للمطوية قبل الطباعة.',
    status: 'completed',
    priority: 'high',
    due_date: '2026-09-07',
    category: 'ترجمة',
    user_id: 'demo-employee-2', // فاطمة
    created_at: '2026-09-03T11:00:00Z',
    updated_at: '2026-09-03T11:00:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[2],
  },
  {
    id: 'task-5',
    title: 'رفع التقرير المالي لمصروفات البرامج لشهر صفر',
    description: 'مطابقة الفواتير والسندات ورفع مسير المكافآت للإدارة المالية.',
    status: 'in_progress',
    priority: 'urgent',
    due_date: '2026-09-11',
    category: 'مالية',
    user_id: 'demo-employee-3', // مريم
    created_at: '2026-09-06T12:00:00Z',
    updated_at: '2026-09-06T12:00:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[3],
  },
  {
    id: 'task-6',
    title: 'حصر ومتابعة المهتدين الجدد لشهر محرم',
    description: 'التواصل الهاتفي مع المهتدين وإرسال جدول الدروس الأساسية.',
    status: 'not_started',
    priority: 'medium',
    due_date: '2026-09-14',
    category: 'برامج دعوية',
    user_id: 'demo-employee-id', // سارة
    created_at: '2026-09-07T08:30:00Z',
    updated_at: '2026-09-07T08:30:00Z',
    profiles: INITIAL_DEMO_EMPLOYEES[1],
  },
];
