import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e8eef7",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f6f9ff",
        "on-secondary-container": "#316e52",
        "on-tertiary-fixed-variant": "#005235",
        "secondary-container": "#aeeecb",
        "on-primary-fixed-variant": "#274e3d",
        "on-primary-fixed": "#002114",
        "on-tertiary-container": "#53b889",
        "on-surface-variant": "#414844",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#75daa8",
        "surface-dim": "#d4dbe3",
        "background": "#f6f9ff",
        "outline-variant": "#c1c8c2",
        "surface-variant": "#dce3ec",
        "inverse-on-surface": "#ebf1fa",
        "tertiary-container": "#00452c",
        "on-secondary-fixed": "#002114",
        "surface-container-high": "#e2e9f1",
        "secondary": "#2c694e",
        "on-primary-container": "#86af99",
        "outline": "#717973",
        "secondary-fixed": "#b1f0ce",
        "on-tertiary-fixed": "#002113",
        "on-background": "#151c22",
        "primary-fixed-dim": "#a5d0b9",
        "surface-container-highest": "#dce3ec",
        "secondary-fixed-dim": "#95d4b3",
        "surface-container-low": "#eef4fd",
        "surface": "#f6f9ff",
        "on-primary": "#ffffff",
        "primary": "#012d1d",
        "inverse-primary": "#a5d0b9",
        "primary-fixed": "#c1ecd4",
        "on-secondary-fixed-variant": "#0e5138",
        "tertiary": "#002d1b",
        "primary-container": "#1b4332",
        "tertiary-fixed": "#92f7c3",
        "surface-tint": "#3f6653",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2a3138",
        "on-surface": "#151c22",
      },
      spacing: {
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "space-xxs": "0.25rem",
        "margin-desktop": "2.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.5rem",
        "margin-tablet": "1.5rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        sans: ["'IBM Plex Sans Arabic'", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
